-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2019-06-02 13:42:34.11

-- foreign keys
Alter TABLE GR05_ALQUILER
    DROP CONSTRAINT UQ_GR05_alquiler_fecha_valida;

DROP TRIGGER TR_GR05_peso_valido on gr05_mov_entrada;
DROP FUNCTION FN_GR05_funcion_comprobar_peso();

ALTER TABLE gr05_posicion
    DROP CONSTRAINT UQ_GR05_posicion_tipo_posicion_valida;

DROP FUNCTION FN_GR05_pos_libres(date);

DROP FUNCTION FN_GR05_vencimiento_alquiler(INTEGER);

DROP VIEW GR05_pos_libres;

DROP VIEW GR05_dinero_invertido;

drop function fn_gr05_pos_libres_fecha(date);

drop function fn_gr05_pos_ocupadas_cliente(integer);


ALTER TABLE GR05_FILA
    DROP CONSTRAINT FK_FILA_ESTANTERIA;

ALTER TABLE GR05_MOV_INTERNO
    DROP CONSTRAINT FK_GR05MOV_INTERNO_MOV_INTERNO;

ALTER TABLE GR05_ALQUILER
    DROP CONSTRAINT FK_GR05_ALQUILER_CLIENTE;

ALTER TABLE GR05_ALQUILER_POSICIONES
    DROP CONSTRAINT FK_GR05_ALQUILER_POSICIONES_ALQUILER;

ALTER TABLE GR05_ALQUILER_POSICIONES
    DROP CONSTRAINT FK_GR05_ALQUILER_POSICIONES_POSICION;

ALTER TABLE GR05_MOV_ENTRADA
    DROP CONSTRAINT FK_GR05_MOV_ENTRADA_ALQUILER_POSICIONES;

ALTER TABLE GR05_MOV_ENTRADA
    DROP CONSTRAINT FK_GR05_MOV_ENTRADA_PALLET;

ALTER TABLE GR05_MOV_INTERNO
    DROP CONSTRAINT FK_GR05_MOV_INTERNO_MOVIMIENTO;

ALTER TABLE GR05_MOV_INTERNO
    DROP CONSTRAINT FK_GR05_MOV_INTERNO_MOV_ENTRADA;

ALTER TABLE GR05_MOV_INTERNO
    DROP CONSTRAINT FK_GR05_MOV_INTERNO_POSICION;

ALTER TABLE GR05_MOV_SALIDA
    DROP CONSTRAINT FK_GR05_MOV_SALIDA_MOVIMIENTO;

ALTER TABLE GR05_MOV_SALIDA
    DROP CONSTRAINT FK_GR05_MOV_SALIDA_MOV_ENTRADA;

ALTER TABLE GR05_POSICION
    DROP CONSTRAINT FK_GR05_POSICION_FILA;

ALTER TABLE GR05_MOV_ENTRADA
    DROP CONSTRAINT FK_MOV_ENTRADA_MOVIMIENTO;

-- tables
DROP TABLE GR05_ALQUILER;

DROP TABLE GR05_ALQUILER_POSICIONES;

DROP TABLE GR05_CLIENTE;

DROP TABLE GR05_ESTANTERIA;

DROP TABLE GR05_FILA;

DROP TABLE GR05_MOVIMIENTO;

DROP TABLE GR05_MOV_ENTRADA;

DROP TABLE GR05_MOV_INTERNO;

DROP TABLE GR05_MOV_SALIDA;

DROP TABLE GR05_PALLET;

DROP TABLE GR05_POSICION;

-- End of file.



